[[main]]
name = "About"
pageRef = "About"
weight = 1

[[main]]
name = "Vision"
pageRef = "whitepaper"
weight = 2

[[main]]
name = "Methodology"
pageRef = "smd-methodology"
weight = 3

[[main]]
name = "projects"
pageRef = "Tags/projects"
weight = 4

[[main]]
name = "Blog"
pageRef = "Blog"
weight = 5

[[main]]
name = "Contact"
pageRef = "Contact"
weight = 6





[[footer]]
name = "Tags"
pageRef = "Tags"
weight = 21

[[footer]]
name = "FAQs"
pageRef = "FAQs"
weight = 22

[[footer]]
name = "Privacy Policy"
pageRef = "Legal"
weight = 23

[[footer]]
name = "Website Stack"
pageRef = "WebsiteStack"
weight = 24
