[[main]]
name = "关于"
pageRef = "About"
weight = 1

[[main]]
name = "愿景"
pageRef = "whitepaper"
weight = 2

[[main]]
name = "方法论"
pageRef = "smd-methodology"
weight = 3

[[main]]
name = "项目"
pageRef = "Tags/项目"
weight = 4

[[main]]
name = "博客"
pageRef = "Blog"
weight = 5

[[main]]
name = "联系"
pageRef = "Contact"
weight = 6



[[footer]]
  name = "社交媒体"
  pageRef = "#"
  weight = 21

[[footer]]
  name = "问答集锦"
  pageRef = "FAQs"
  weight = 22

[[footer]]
name = "隐私政策"
pageRef = "Legal"
weight = 23

[[footer]]
  name = "标签导航"
  pageRef = "Tags"
  weight = 24

[[footer]]
name = "网站架构"
pageRef = "WebsiteStack"
weight = 25