[[main]]
  name = "About"
  pageRef = "About"
  weight = 1

[[main]]
  name = "Vision"
  pageRef = "whitepaper"
  weight = 2

[[main]]
  name = "Theory"
  weight = 3

  [[main]]
  name = "SMD Methodology"
  parent = "Theory"
  pageRef = "smd-methodology"
  weight = 31
  
  [[main]]
  name = "SMD System Therapy"
  parent = "Theory"
  pageRef = "wiki"
  weight = 32
      
  [[main]]
  name = "HHI Project Wiki"
  parent = "Theory"
  url = "https://github.com/hhpf/"
  weight = 33

[[main]]
  name = "Projects"
  weight = 5

  [[main]]
    name = "Coaching Program"
    parent = "Projects"
    weight = 51
    pageRef = "/whitepaper/smd-club/"
  
  [[main]]
    name = "AI Initiative"
    parent = "Projects"
    weight = 52
    pageRef = "/whitepaper/smd-ai/"
  
  [[main]]
    name = "Medical Clinics"
    parent = "Projects"
    weight = 53
    pageRef = "/whitepaper/smd-medical-hall/"
  
  [[main]]
    name = "Rehabilitation Centers"
    parent = "Projects"
    weight = 54
    pageRef = "/whitepaper/smd-center/"
  
  [[main]]
    name = "Health Industry Park"
    parent = "Projects"
    weight = 55
    pageRef = "/whitepaper/smd-park/"
  
  [[main]]
    name = "Community Wellness Complex"
    parent = "Projects"
    weight = 56
    pageRef = ""
  
  [[main]]
    name = "Life Health Academy"
    parent = "Projects"
    weight = 57
    pageRef = "/whitepaper/smd-college/"

[[main]]
  name = "Blog"
  pageRef = "Blog"
  weight = 6

[[main]]
  name = "Contact"
  pageRef = "Contact"
  weight = 7

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/HHI-Foundation/home"
  weight = 8



[[footer]]
  name = "SM"
  pageRef = "#"
  weight = 21

[[footer]]
  name = "FAQs"
  pageRef = "FAQs"
  weight = 22

[[footer]]
  name = "Privacy Policy"
  pageRef = "Legal"
  weight = 23

[[footer]]
  name = "Website Stack"
  pageRef = "WebsiteStack"
  weight = 24